default: &default
  DB_HOST: ""
  DB_PORT: "5432"
  USERNAME: "postgres"
  MAILER_DEFAULT_HOST: "localhost"
  MAILER_DEFAULT_PORT: "3000"
  MAILER_SENDER: "Test <noreply@nimbl3.co>"
  GOOGLE_CLIENT_ID: "677107366813-tktjcff5sfr58qo6vpuq8l2f8f55hqkk.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET: "hkWewiLjcOyWtSioT8gYqzi-"

development:
  <<: *default
  DB_NAME: "google_scraper_development"
  SECRET_KEY_BASE: "#{secret_key_base}"

test:
  <<: *default
  DB_NAME: "google_scraper_test"
  TEST_RETRY: "0"
  SECRET_KEY_BASE: "#{secret_key_base}"
